title: "ABE Media"
description: "We're a small, yet highly innovative web design and development company based in Brighton &amp; Hove, East Sussex. Since its incorporation in 2005, ABE Media have been at the forefront of new technology, shaping the future of web design with each and every project."
keywords: web design brighton, web development, joomla development, ecommerce
baseurl: /
url: http://abemedia.co.uk
timezone: Europe/London
image: /images/donjoomla.png
locale: en_GB
permalink: /:categories/:title.html
layout: default
disqus_shortname: abemedia
author: Adam Bouqdib
markdown: kramdown
gems:
  - jekyll-sitemap
relative_permalinks: false

facebook_app: 276049565908648
twitter: abemedia
v: 31